# Generated by Django 3.2.9 on 2022-02-09 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality_name', models.CharField(max_length=30)),
                ('quality_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Quality',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeeOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TypeeOrder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30)),
                ('store_logo', models.ImageField(null=True, upload_to='store_logo/')),
                ('store_img', models.ImageField(null=True, upload_to='store_img/')),
                ('store_address', models.CharField(max_length=255)),
                ('store_description', models.CharField(max_length=255)),
                ('store_phone', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('bank_account', models.CharField(max_length=30)),
                ('bank_id', models.CharField(max_length=13)),
                ('name_bank', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Store',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('melon_color', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('product_weight', models.FloatField(blank=True, default=None, null=True)),
                ('product_amount', models.IntegerField()),
                ('range', models.IntegerField()),
                ('product_image', models.ImageField(null=True, upload_to='product_image/')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('date_expire', models.DateField(null=True)),
                ('date_harvest', models.DateField(null=True)),
                ('plant_place', models.CharField(max_length=255)),
                ('water_source', models.CharField(max_length=255)),
                ('shipping_cost', models.IntegerField()),
                ('select_carving', models.BooleanField()),
                ('cost_carving', models.IntegerField()),
                ('quality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.quality')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.typeeorder')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
    ]
