# Generated by Django 3.2.9 on 2021-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='bank_account',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='bank_id',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='store',
            name='name_bank',
            field=models.CharField(max_length=50),
        ),
    ]
