# Generated by Django 3.2.9 on 2021-12-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211210_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Store_id',
            new_name='store_id',
        ),
    ]
