# Generated by Django 3.2.9 on 2022-02-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211216_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
