# Generated by Django 3.2.9 on 2022-02-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='melon_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='plant_place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_source',
            field=models.CharField(max_length=255),
        ),
    ]
