# Generated by Django 3.2.9 on 2022-02-09 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Typeuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.typeuser')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserInType',
                'managed': True,
            },
        ),
    ]
