# Generated by Django 3.2.9 on 2022-02-09 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_name', models.CharField(max_length=50)),
                ('bug_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Bug',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=50)),
                ('disease_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Disease',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('shipping_cost', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'State',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_description', models.CharField(max_length=255)),
                ('review_image', models.ImageField(upload_to='reviews/')),
                ('review_rating', models.IntegerField()),
                ('date_send', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'Review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recode_date', models.DateTimeField(auto_now=True)),
                ('recode_description', models.CharField(max_length=255)),
                ('recode_image', models.ImageField(upload_to='recode_image/')),
                ('recode_weight', models.FloatField()),
                ('sweetness', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('quality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.quality')),
            ],
            options={
                'db_table': 'Record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Portage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portage_name', models.CharField(max_length=255)),
                ('portage_number', models.CharField(max_length=20)),
                ('date_send', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'Portage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_image', models.ImageField(upload_to='payment_image/')),
                ('bank_name', models.CharField(max_length=100)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'Payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderCarving',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='img_Ordercarving/')),
                ('carving_description', models.CharField(max_length=255)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'OrderCarving',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='State_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.state'),
        ),
        migrations.AddField(
            model_name='order',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'Message',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cancel_description', models.CharField(max_length=255)),
                ('refund_contact', models.CharField(max_length=255)),
                ('bug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.bug')),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.disease')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'CancelOrder',
                'managed': True,
            },
        ),
    ]
