# Generated by Django 3.2.9 on 2022-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='covert_image',
            field=models.ImageField(null=True, upload_to='covert_image/'),
        ),
    ]
