# Generated by Django 3.2.9 on 2022-03-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_record_covert_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='covert_image',
        ),
        migrations.CreateModel(
            name='CovertImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('covert_image', models.ImageField(null=True, upload_to='covert_image/')),
                ('recode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.record')),
            ],
            options={
                'db_table': 'CovertImage',
                'managed': True,
            },
        ),
    ]
